Travel.Api/Travel.Api.Client.Web/Models/DistanceMatrixResultsViewModel.cs
namespace Travel.Api.Client.Web.Models
{

    using System.Collections.Generic;

    public class DistanceMatrixResultsViewModel
	{
		public string Origins { get; set; }

		public string Destinations { get; set; }

		public List<string> Results { get; set; }
	}
}

Travel.Api/Travel.Api.Client.Web/Models/RequestHistoryViewModel.cs
namespace Travel.Api.Client.Web.Models
{

    using System;

    public class RequestHistoryViewModel
	{
		public Guid Id { get; set; }

		public string Origins { get; set; }

		public string Destinations { get; set; }
	}
}

Travel.Api/Travel.Api.Client.Web/Controllers/DistanceMatrixController.cs
namespace Travel.Api.Client.Web.Controllers
{

    using Domain.Enums;
    using Domain.Models;
    using Models;

    public class DistanceMatrixController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Index(DistanceMatrixRequest distanceMatrixRequest)
		{
			var serviceClient = new GoogleApiService.GoogleApiServiceClient();
			var distanceMatrixResponse = serviceClient.DistanceMatrix(distanceMatrixRequest);
			if (distanceMatrixResponse.IsSuccessful)
			{
				if (distanceMatrixResponse.Response.Status == Status.Ok)
				{
					var distanceMatrixResults = ControllerHelper.MapResponseToViewModel(distanceMatrixResponse.Response);
					return View("Results", distanceMatrixResults);
				}
			}

			return View("Error", distanceMatrixResponse.ErrorMessage);
		}

		public ActionResult Results(DistanceMatrixResultsViewModel distanceMatrixResults)
		{
			return View("Results", distanceMatrixResults);
		}
	}
}

Travel.Api/Travel.Api.Client.Web/Controllers/HomeController.cs
namespace Travel.Api.Client.Web.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

Travel.Api/Travel.Api.Client.Web/Controllers/RequestHistoryController.cs
namespace Travel.Api.Client.Web.Controllers
{

    using System;
    using System.Collections.Generic;
    using Models;

    public class RequestHistoryController : Controller
    {
		public ActionResult Index()
		{
			var serviceClient = new GoogleApiService.GoogleApiServiceClient();
			var response = serviceClient.GetDistanceMatrixRequestHistory();
			if (response.IsSuccessful)
			{
				var viewModel = new List<RequestHistoryViewModel>();
				foreach(var rh in response.Response)
				{
					viewModel.Add(new RequestHistoryViewModel
					{
						Id = rh.Id,
						Origins = rh.Request.Origins,
						Destinations = rh.Request.Destinations
					});
				}

				return View("Index", viewModel);
			}

			return View("Error", response.ErrorMessage);
		}

		public ActionResult Delete(Guid id)
		{
			var serviceClient = new GoogleApiService.GoogleApiServiceClient();
			var response = serviceClient.DeleteRequestHistory(id);
			if (response.IsSuccessful)
			{
				return RedirectToAction("Index");
			}

			return View("Error", response.ErrorMessage);
		}

		public ActionResult Replay(Guid id)
		{
			var serviceClient = new GoogleApiService.GoogleApiServiceClient();
			var distanceMatrixResponse = serviceClient.ReplayRequest(id);
			if (distanceMatrixResponse.IsSuccessful)
			{
				var distanceMatrixResults = ControllerHelper.MapResponseToViewModel(distanceMatrixResponse.Response);
				return View("Results", distanceMatrixResults);
			}

			return View("Error", distanceMatrixResponse.ErrorMessage);
		}
	}
}

Travel.Api/Travel.Api.Client.Web/Views/DistanceMatrix/Index.cshtml
@model DistanceMatrix.Domain.Models.DistanceMatrixRequest

@{
    ViewBag.Title = "Distance Matrix";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Origins, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origins, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origins, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destinations, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destinations, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destinations, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(
                    x => x.Mode,
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Mode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Units, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(
                    x => x.Units,
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Units)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Travel.Api/Travel.Api.Client.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Google API</h1>
    <p class="lead">Sample MVC application to show Google Api.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Distance Matrix API</h2>
        <p>The Google Distance Matrix API makes it easy to search for the distance between one or more places.</p>
        <p>@Html.ActionLink("Distance Matrix", "Index", "Distance Matrix")</p>
    </div>
    <div class="col-md-4">
        <h2>Request History</h2>
        <p>You can view a list of previous search requests. These requests are held in-memory and the requests can be replayed through this web application.</p>
        <p>@Html.ActionLink("Request History", "Index", "RequestHistory")</p>
    </div>
</div>

Travel.Api/Travel.Api.Client.Web/Views/RequestHistory/Index.cshtml
@model IEnumerable<DistanceMatrix.Client.Web.Models.RequestHistoryViewModel>
@{
    ViewBag.Title = "Request History";
}
<h2>@ViewBag.Title</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Origins)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destinations)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Origins)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destinations)
        </td>
        <td>
            @Html.ActionLink("Replay", "Replay", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Travel.Api/Travel.Api.Client.Web/Views/Shared/Results.cshtml
@model DistanceMatrix.Client.Web.Models.DistanceMatrixResultsViewModel

@{
    ViewBag.Title = "Distance Matrix Results";
}

<h2>@ViewBag.Title</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Origins)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origins)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destinations)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destinations)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Results)
        </dt>

        <dd>
            @foreach (var result in Model.Results)
            {
                @result
                @Html.Raw("<br/>")
            }
        </dd>
    </dl>
</div>

Travel.Api/Travel.Api.Client.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Google Api Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Google Api", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Distance Matrix", "Index", "DistanceMatrix")</li>
                    <li>@Html.ActionLink("Request History", "Index", "RequestHistory")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Google Api Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>